name: av_account
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

  fonts:
    - family: Acumin-Pro
      fonts:
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Regular.ttf
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Black.ttf
          weight: 900
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Bold.ttf
          weight: 700
        - asset: assets/fonts/acumin_pro/Acumin-Pro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Medium.ttf
          weight: 500
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Light.ttf
          weight: 300
        - asset: assets/fonts/acumin_pro/Acumin-Pro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/acumin_pro/Acumin-Pro-Thin.ttf
          weight: 100

    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/ubuntu/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/ubuntu/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/ubuntu/Ubuntu-MediumItalic.ttf
          weight: 500
          style: italic
